<a href="https://colab.research.google.com/github/abcardoso/ifes_ai/blob/main/IA_GeneticAlgorithm_8queens_Solucao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Teste de implementação em phyton do Algoritmo Genético.
Obs.:

# Algoritmo Genético
## Para o problema das 8 rainhas

## Importações

In [2]:
# Manipulação de dados
import numpy as np
#import pandas as pd

# Geração de números aleatórios
import random

In [3]:
#VT = np.array([4,8,2,7,3,1,5,6])
VT = np.array([4,8,2,7,3,7,5,4])

VT

array([4, 8, 2, 7, 3, 7, 5, 4])

## Funções Auxiliares - Problema

### Converte Vetor em Tabuleiro

In [4]:
def converte_tabuleiro(VT):
    '''
    Recebe um vetor representando um tabuleiro
    com N rainhas, uma por coluna e retorna
    uma lista de lista de 0 e 1 representando
    um tabuleiro com as rainhas.
    '''
    N = len(VT)

    L = [0]*N
    T = []
    for i in range(N):
        T += [L.copy()]

    for lin in range(N):
        for col in range(N):
            if lin+1 == VT[col]:
                T[lin][col] = 1

    return T

In [ ]:
converte_tabuleiro(VT)

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0]]

### Calcula custo (Fitness)

In [6]:
def __conta_ataques_linhas(VT):
    '''
    Função que recebe um Vetor-Tabuleiro e
    retorna o número de pares de rainhas se
    atacando mutuamente nas linhas.
    '''
    ataques = 0
    N = len(VT)
    for col1 in range(N):
        lin1 = VT[col1]
        for col2 in range(col1+1, N):
            lin2 = VT[col2]
            if lin1==lin2:
                ataques +=1

    return ataques

In [ ]:
__conta_ataques_linhas(VT)

2

In [7]:
def __conta_ataques_diagonais(VT):
    '''
    Função que recebe um Vetor-Tabuleiro e
    retorna o número de pares de rainhas se
    atacando mutuamente nas diagonais.
    '''
    ataques = 0
    N = len(VT)

    for col1 in range(N):
        lin1 = VT[col1]
        for col2 in range(col1+1, N):
            lin2 = VT[col2]

            # diferenças entre as linhas e colunas
            d1 = lin1-col1
            d2 = lin2-col2

            # somas das linhas e colunas
            s1 = lin1+col1
            s2 = lin2+col2

            # condições para ataques nas diagonais
            if d1==d2 or s1==s2:
                ataques +=1
                #print(f'({lin1},{col1+1}) ({lin2},{col2+1}) -->', ataques,
                #      '<--', f'  -({d1:2},{d2:2})  +({s1:2},{s2:2})')

    return ataques

In [ ]:
converte_tabuleiro(VT)

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0]]

In [ ]:
__conta_ataques_diagonais(VT)

4

In [8]:
def conta_ataques(VT):
    '''
    Função que recebe um Vetor-Tabuleiro e
    retorna o número de pares de rainhas se
    atacando mutuamente nas linhas e diagonais.
    '''
    ataques  = __conta_ataques_linhas(VT)

    ataques += __conta_ataques_diagonais(VT)

    return ataques

In [ ]:
VT = [1,2,3,4,5,6,7,8]

In [9]:
conta_ataques(VT)

6

### Gera vizinhos

In [11]:
def gera_vizinhos(VT):
    '''
    Gera todos os vizinhos possíveis,
    variando uma rainha de cada vez.
    '''
    N = len(VT)
    for col in range(N):
        for lin in range(N):
            # se nao existe rainha naquela linha,
            # entao gera estado vizinho.
            linha = lin+1
            if linha != VT[col]:
                vizinho   = VT.copy()
                vizinho[col] = linha

                yield vizinho


### Gera tuplas custos

In [12]:
def gera_tuplas_custos(Populacao):
    '''
    Gera tuplas com os custos de todos os individuos da populacao.
    '''
    TuplasCustos = []
    for individuo in Populacao:
        ataques = conta_ataques(individuo)

        TuplasCustos += [(ataques, individuo)]

    return TuplasCustos


In [14]:
Populacao = gera_vizinhos(VT)
Tuplas = gera_tuplas_custos(Populacao)
Tuplas

[(3, array([1, 8, 2, 7, 3, 7, 5, 4])),
 (5, array([2, 8, 2, 7, 3, 7, 5, 4])),
 (4, array([3, 8, 2, 7, 3, 7, 5, 4])),
 (4, array([5, 8, 2, 7, 3, 7, 5, 4])),
 (3, array([6, 8, 2, 7, 3, 7, 5, 4])),
 (7, array([7, 8, 2, 7, 3, 7, 5, 4])),
 (4, array([8, 8, 2, 7, 3, 7, 5, 4])),
 (7, array([4, 1, 2, 7, 3, 7, 5, 4])),
 (7, array([4, 2, 2, 7, 3, 7, 5, 4])),
 (10, array([4, 3, 2, 7, 3, 7, 5, 4])),
 (8, array([4, 4, 2, 7, 3, 7, 5, 4])),
 (9, array([4, 5, 2, 7, 3, 7, 5, 4])),
 (7, array([4, 6, 2, 7, 3, 7, 5, 4])),
 (8, array([4, 7, 2, 7, 3, 7, 5, 4])),
 (7, array([4, 8, 1, 7, 3, 7, 5, 4])),
 (6, array([4, 8, 3, 7, 3, 7, 5, 4])),
 (8, array([4, 8, 4, 7, 3, 7, 5, 4])),
 (7, array([4, 8, 5, 7, 3, 7, 5, 4])),
 (7, array([4, 8, 6, 7, 3, 7, 5, 4])),
 (8, array([4, 8, 7, 7, 3, 7, 5, 4])),
 (7, array([4, 8, 8, 7, 3, 7, 5, 4])),
 (6, array([4, 8, 2, 1, 3, 7, 5, 4])),
 (7, array([4, 8, 2, 2, 3, 7, 5, 4])),
 (6, array([4, 8, 2, 3, 3, 7, 5, 4])),
 (7, array([4, 8, 2, 4, 3, 7, 5, 4])),
 (6, array([4, 8, 2, 5, 

In [15]:
sorted(Tuplas, key=lambda k: k[0])

[(3, array([1, 8, 2, 7, 3, 7, 5, 4])),
 (3, array([6, 8, 2, 7, 3, 7, 5, 4])),
 (4, array([3, 8, 2, 7, 3, 7, 5, 4])),
 (4, array([5, 8, 2, 7, 3, 7, 5, 4])),
 (4, array([8, 8, 2, 7, 3, 7, 5, 4])),
 (4, array([4, 8, 2, 7, 3, 7, 5, 1])),
 (5, array([2, 8, 2, 7, 3, 7, 5, 4])),
 (5, array([4, 8, 2, 6, 3, 7, 5, 4])),
 (5, array([4, 8, 2, 7, 3, 1, 5, 4])),
 (5, array([4, 8, 2, 7, 3, 7, 1, 4])),
 (5, array([4, 8, 2, 7, 3, 7, 2, 4])),
 (5, array([4, 8, 2, 7, 3, 7, 5, 8])),
 (6, array([4, 8, 3, 7, 3, 7, 5, 4])),
 (6, array([4, 8, 2, 1, 3, 7, 5, 4])),
 (6, array([4, 8, 2, 3, 3, 7, 5, 4])),
 (6, array([4, 8, 2, 5, 3, 7, 5, 4])),
 (6, array([4, 8, 2, 7, 1, 7, 5, 4])),
 (6, array([4, 8, 2, 7, 2, 7, 5, 4])),
 (6, array([4, 8, 2, 7, 3, 3, 5, 4])),
 (6, array([4, 8, 2, 7, 3, 8, 5, 4])),
 (6, array([4, 8, 2, 7, 3, 7, 6, 4])),
 (6, array([4, 8, 2, 7, 3, 7, 7, 4])),
 (6, array([4, 8, 2, 7, 3, 7, 8, 4])),
 (6, array([4, 8, 2, 7, 3, 7, 5, 2])),
 (6, array([4, 8, 2, 7, 3, 7, 5, 3])),
 (6, array([4, 8, 2, 7, 3

## Funções Auxiliares - AG

### Mutação

In [16]:
def mutacao(VT, p_mutacao=0.30):

    VT_mutated = VT.copy()

    N = len(VT)
    p = np.random.rand()

    if p < p_mutacao:
        col   = np.random.randint(0,N)    # indice da coluna (base-0)
        linha = np.random.randint(1,N+1)  # valor da linha   (base-1)

        VT_mutated[col] = linha
        #print(col+1, linha)

    return VT_mutated

In [17]:
VT

array([4, 8, 2, 7, 3, 7, 5, 4])

In [18]:
VT2 = mutacao(VT)
VT, VT2, VT != VT2

(array([4, 8, 2, 7, 3, 7, 5, 4]),
 array([4, 8, 2, 2, 3, 7, 5, 4]),
 array([False, False, False,  True, False, False, False, False]))

### Crossover

In [45]:
def crossover(Parent1, Parent2):

    N = len(Parent1)

    # ponto de corte
    c = np.random.randint(1, N-1)

    # crossover no ponto de corte
    # gerando dois filhos
    child1 = list(Parent1[:c]) + list(Parent2[c:])
    child2 = list(Parent2[:c]) + list(Parent1[c:])

    return child1, child2

In [46]:
VT1 = [1,1,1,1,1,1,1,1]
VT2 = [2,2,2,2,2,2,2,2]

In [47]:
crossover(VT1,VT2)

([1, 1, 1, 1, 2, 2, 2, 2], [2, 2, 2, 2, 1, 1, 1, 1])

### Seleciona pais

In [38]:
# Selecao por torneio
def selecao(Populacao):
    Candidato1 = random.choice(Populacao)
    Candidato2 = random.choice(Populacao)

    a1 = conta_ataques(Candidato1)
    a2 = conta_ataques(Candidato2)
    #print(a1,a2)

    # eleito o candidato com menor custo
    eleito = Candidato1 if a1<=a2 else Candidato2

    return eleito


In [26]:
selecao([VT1,VT2],VT)

[1, 1, 1, 1, 1, 1, 1, 1]

### Gera Indivíduo

In [27]:
def gera_individuo(n_cols):
    # individuo é um Vetor (N) em que cada posicação
    # representa uma coluna indicando as respectivas
    # linhas ocupadas pelas rainhas em um tabuleiro (NxN).

    # VT = [low, high) x n_cols

    VT = np.random.randint(low=1, high=n_cols+1, size=n_cols)
    return VT

In [28]:
N=8
gera_individuo(N)

array([7, 2, 5, 7, 4, 6, 1, 5])

### Gera População

In [29]:
def gera_populacao_inicial(N, tam_pop):
    # N:       tamanho do tabuleiro (NxN)
    # tam_pop: tamanho da população
    populacao = []
    for _ in range(tam_pop):
        individuo = gera_individuo(N)

        populacao.append(individuo)

    return populacao

In [42]:
N = 8
tam_pop = 100
gera_populacao_inicial(N, tam_pop)

[array([5, 5, 7, 8, 4, 8, 2, 7]),
 array([2, 8, 6, 6, 7, 5, 3, 7]),
 array([5, 8, 6, 6, 2, 8, 2, 2]),
 array([1, 8, 7, 4, 7, 1, 3, 8]),
 array([5, 1, 4, 4, 1, 5, 1, 8]),
 array([1, 4, 2, 7, 1, 1, 3, 7]),
 array([3, 8, 5, 6, 3, 8, 3, 4]),
 array([3, 3, 2, 8, 1, 1, 1, 6]),
 array([4, 5, 8, 6, 8, 3, 5, 5]),
 array([8, 6, 8, 6, 4, 1, 5, 5]),
 array([1, 5, 7, 4, 2, 3, 5, 4]),
 array([6, 5, 8, 6, 8, 7, 5, 5]),
 array([5, 7, 1, 8, 7, 3, 1, 2]),
 array([3, 4, 6, 4, 1, 1, 6, 4]),
 array([8, 7, 7, 2, 7, 5, 1, 4]),
 array([7, 8, 6, 2, 8, 2, 3, 5]),
 array([1, 2, 3, 3, 3, 6, 6, 5]),
 array([6, 2, 4, 6, 3, 6, 1, 4]),
 array([3, 2, 7, 1, 4, 4, 1, 2]),
 array([6, 2, 6, 3, 2, 4, 3, 2]),
 array([4, 7, 6, 2, 4, 4, 3, 3]),
 array([4, 4, 4, 2, 1, 1, 5, 6]),
 array([4, 6, 3, 5, 4, 4, 8, 2]),
 array([3, 2, 4, 4, 6, 2, 6, 5]),
 array([7, 5, 3, 7, 6, 3, 4, 6]),
 array([8, 6, 8, 5, 1, 4, 1, 6]),
 array([3, 2, 5, 3, 1, 4, 7, 3]),
 array([8, 8, 4, 5, 5, 2, 8, 4]),
 array([2, 1, 8, 1, 1, 4, 5, 3]),
 array([6, 8, 

## Algoritmo Genético - Implementação

In [ ]:
# 1) Randomly initialize populations p
# 2) Compute fitness of population
# 3) Until convergence repeat:
#       a) Select parents from population
#       b) Crossover and generate new population
#       c) Perform mutation on new population
# 4) Calculate fitness for new population

In [48]:
def algoritmo_genetico(N, tam_pop, num_geracoes, taxa_mutacao):
    solucoes_encontradas = 0
    geracoes_necessarias = []

    for i in range(tam_pop):  # Gerar 100 exemplos
        Populacao = gera_populacao_inicial(N, tam_pop)
        TuplasCustos = gera_tuplas_custos(Populacao)
        Populacao = [t[1] for t in sorted(TuplasCustos, key=lambda x: x[0])]  # Ordena pela fitness

        print(f"tam_pop atual: {i}")

        for geracao in range(num_geracoes):
            nova_populacao = []
            while len(nova_populacao) < tam_pop:
                pai1 = selecao(Populacao)
                pai2 = selecao(Populacao)
                filho1, filho2 = crossover(pai1, pai2)
                filho1 = mutacao(filho1, taxa_mutacao)
                filho2 = mutacao(filho2, taxa_mutacao)
                nova_populacao.extend([filho1, filho2])

            TuplasCustos = gera_tuplas_custos(nova_populacao)
            nova_populacao = [t[1] for t in sorted(TuplasCustos, key=lambda x: x[0])]  # Ordena pela fitness
            melhor_fitness_atual = TuplasCustos[0][0]

            if melhor_fitness_atual == 0:
                solucoes_encontradas += 1
                geracoes_necessarias.append(geracao + 1)
                break
            Populacao = nova_populacao

        if melhor_fitness_atual > 0:
            geracoes_necessarias.append(num_geracoes)  # Máximo se não encontrar solução

    percentual_resolvidos = (solucoes_encontradas / 100.0) * 100
    custo_medio = sum(geracoes_necessarias) / len(geracoes_necessarias)
    return percentual_resolvidos, custo_medio



In [50]:
# Configurações do algoritmo
N = 8  # tamanho do tabuleiro 8 x 8
tam_pop = 100  # tamanho da população
num_geracoes = 1000  # número máximo de gerações
taxa_mutacao = 0.1  # taxa de mutação

percentual_resolvidos, custo_medio = algoritmo_genetico(N, tam_pop, num_geracoes, taxa_mutacao)
print(f"Percentual de problemas resolvidos: {percentual_resolvidos}%")
print(f"Custo médio da busca (em gerações): {custo_medio}")

Percentual de problemas resolvidos: 55.00000000000001%
Custo médio da busca (em gerações): 552.05
