<a href="https://colab.research.google.com/github/abcardoso/ifes_ai/blob/main/IA_GeneticAlgorithm_8queens_Solucao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Teste de implementação em phyton do Algoritmo Genético.
Obs.:

# Algoritmo Genético
## Para o problema das 8 rainhas

## Importações

In [85]:
# Manipulação de dados
import numpy as np
#import pandas as pd

# Geração de números aleatórios
import random

In [86]:
#VT = np.array([4,8,2,7,3,1,5,6])
VT = np.array([4,8,2,7,3,7,5,4])

VT

array([4, 8, 2, 7, 3, 7, 5, 4])

## Funções Auxiliares - Problema

### Converte Vetor em Tabuleiro

In [87]:
def converte_tabuleiro(VT):
    '''
    Recebe um vetor representando um tabuleiro
    com N rainhas, uma por coluna e retorna
    uma lista de lista de 0 e 1 representando
    um tabuleiro com as rainhas.
    '''
    N = len(VT)

    L = [0]*N
    T = []
    for i in range(N):
        T += [L.copy()]

    for lin in range(N):
        for col in range(N):
            if lin+1 == VT[col]:
                T[lin][col] = 1

    return T

In [88]:
converte_tabuleiro(VT)

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0]]

### Calcula custo (Fitness)

In [89]:
def __conta_ataques_linhas(VT):
    '''
    Função que recebe um Vetor-Tabuleiro e
    retorna o número de pares de rainhas se
    atacando mutuamente nas linhas.
    '''
    ataques = 0
    N = len(VT)
    for col1 in range(N):
        lin1 = VT[col1]
        for col2 in range(col1+1, N):
            lin2 = VT[col2]
            if lin1==lin2:
                ataques +=1

    return ataques

In [90]:
__conta_ataques_linhas(VT)

2

In [91]:
def __conta_ataques_diagonais(VT):
    '''
    Função que recebe um Vetor-Tabuleiro e
    retorna o número de pares de rainhas se
    atacando mutuamente nas diagonais.
    '''
    ataques = 0
    N = len(VT)

    for col1 in range(N):
        lin1 = VT[col1]
        for col2 in range(col1+1, N):
            lin2 = VT[col2]

            # diferenças entre as linhas e colunas
            d1 = lin1-col1
            d2 = lin2-col2

            # somas das linhas e colunas
            s1 = lin1+col1
            s2 = lin2+col2

            # condições para ataques nas diagonais
            if d1==d2 or s1==s2:
                ataques +=1
                #print(f'({lin1},{col1+1}) ({lin2},{col2+1}) -->', ataques,
                #      '<--', f'  -({d1:2},{d2:2})  +({s1:2},{s2:2})')

    return ataques

In [92]:
converte_tabuleiro(VT)

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0]]

In [93]:
__conta_ataques_diagonais(VT)

4

In [94]:
def conta_ataques(VT):
    '''
    Função que recebe um Vetor-Tabuleiro e
    retorna o número de pares de rainhas se
    atacando mutuamente nas linhas e diagonais.
    '''
    ataques  = __conta_ataques_linhas(VT)

    ataques += __conta_ataques_diagonais(VT)

    return ataques

In [95]:
VT = [1,2,3,4,5,6,7,8]

In [96]:
conta_ataques(VT)

28

### Gera vizinhos

In [97]:
def gera_vizinhos(VT):
    '''
    Gera todos os vizinhos possíveis,
    variando uma rainha de cada vez.
    '''
    N = len(VT)
    for col in range(N):
        for lin in range(N):
            # se nao existe rainha naquela linha,
            # entao gera estado vizinho.
            linha = lin+1
            if linha != VT[col]:
                vizinho   = VT.copy()
                vizinho[col] = linha

                yield vizinho


### Gera tuplas custos

In [98]:
def gera_tuplas_custos(Populacao):
    '''
    Gera tuplas com os custos de todos os individuos da populacao.
    '''
    TuplasCustos = []
    for individuo in Populacao:
        ataques = conta_ataques(individuo)

        TuplasCustos += [(ataques, individuo)]

    return TuplasCustos


In [99]:
Populacao = gera_vizinhos(VT)
Tuplas = gera_tuplas_custos(Populacao)
Tuplas

[(22, [2, 2, 3, 4, 5, 6, 7, 8]),
 (23, [3, 2, 3, 4, 5, 6, 7, 8]),
 (22, [4, 2, 3, 4, 5, 6, 7, 8]),
 (23, [5, 2, 3, 4, 5, 6, 7, 8]),
 (22, [6, 2, 3, 4, 5, 6, 7, 8]),
 (23, [7, 2, 3, 4, 5, 6, 7, 8]),
 (22, [8, 2, 3, 4, 5, 6, 7, 8]),
 (22, [1, 1, 3, 4, 5, 6, 7, 8]),
 (22, [1, 3, 3, 4, 5, 6, 7, 8]),
 (23, [1, 4, 3, 4, 5, 6, 7, 8]),
 (22, [1, 5, 3, 4, 5, 6, 7, 8]),
 (23, [1, 6, 3, 4, 5, 6, 7, 8]),
 (22, [1, 7, 3, 4, 5, 6, 7, 8]),
 (23, [1, 8, 3, 4, 5, 6, 7, 8]),
 (23, [1, 2, 1, 4, 5, 6, 7, 8]),
 (22, [1, 2, 2, 4, 5, 6, 7, 8]),
 (22, [1, 2, 4, 4, 5, 6, 7, 8]),
 (23, [1, 2, 5, 4, 5, 6, 7, 8]),
 (22, [1, 2, 6, 4, 5, 6, 7, 8]),
 (23, [1, 2, 7, 4, 5, 6, 7, 8]),
 (22, [1, 2, 8, 4, 5, 6, 7, 8]),
 (22, [1, 2, 3, 1, 5, 6, 7, 8]),
 (23, [1, 2, 3, 2, 5, 6, 7, 8]),
 (22, [1, 2, 3, 3, 5, 6, 7, 8]),
 (22, [1, 2, 3, 5, 5, 6, 7, 8]),
 (23, [1, 2, 3, 6, 5, 6, 7, 8]),
 (22, [1, 2, 3, 7, 5, 6, 7, 8]),
 (23, [1, 2, 3, 8, 5, 6, 7, 8]),
 (23, [1, 2, 3, 4, 1, 6, 7, 8]),
 (22, [1, 2, 3, 4, 2, 6, 7, 8]),
 (23, [1, 

In [100]:
sorted(Tuplas, key=lambda k: k[0])

[(22, [2, 2, 3, 4, 5, 6, 7, 8]),
 (22, [4, 2, 3, 4, 5, 6, 7, 8]),
 (22, [6, 2, 3, 4, 5, 6, 7, 8]),
 (22, [8, 2, 3, 4, 5, 6, 7, 8]),
 (22, [1, 1, 3, 4, 5, 6, 7, 8]),
 (22, [1, 3, 3, 4, 5, 6, 7, 8]),
 (22, [1, 5, 3, 4, 5, 6, 7, 8]),
 (22, [1, 7, 3, 4, 5, 6, 7, 8]),
 (22, [1, 2, 2, 4, 5, 6, 7, 8]),
 (22, [1, 2, 4, 4, 5, 6, 7, 8]),
 (22, [1, 2, 6, 4, 5, 6, 7, 8]),
 (22, [1, 2, 8, 4, 5, 6, 7, 8]),
 (22, [1, 2, 3, 1, 5, 6, 7, 8]),
 (22, [1, 2, 3, 3, 5, 6, 7, 8]),
 (22, [1, 2, 3, 5, 5, 6, 7, 8]),
 (22, [1, 2, 3, 7, 5, 6, 7, 8]),
 (22, [1, 2, 3, 4, 2, 6, 7, 8]),
 (22, [1, 2, 3, 4, 4, 6, 7, 8]),
 (22, [1, 2, 3, 4, 6, 6, 7, 8]),
 (22, [1, 2, 3, 4, 8, 6, 7, 8]),
 (22, [1, 2, 3, 4, 5, 1, 7, 8]),
 (22, [1, 2, 3, 4, 5, 3, 7, 8]),
 (22, [1, 2, 3, 4, 5, 5, 7, 8]),
 (22, [1, 2, 3, 4, 5, 7, 7, 8]),
 (22, [1, 2, 3, 4, 5, 6, 2, 8]),
 (22, [1, 2, 3, 4, 5, 6, 4, 8]),
 (22, [1, 2, 3, 4, 5, 6, 6, 8]),
 (22, [1, 2, 3, 4, 5, 6, 8, 8]),
 (22, [1, 2, 3, 4, 5, 6, 7, 1]),
 (22, [1, 2, 3, 4, 5, 6, 7, 3]),
 (22, [1, 

## Funções Auxiliares - AG

### Mutação

In [101]:
def mutacao(VT, p_mutacao=0.30):

    VT_mutated = VT.copy()

    N = len(VT)
    p = np.random.rand()

    if p < p_mutacao:
        col   = np.random.randint(0,N)    # indice da coluna (base-0)
        linha = np.random.randint(1,N+1)  # valor da linha   (base-1)

        VT_mutated[col] = linha
        #print(col+1, linha)

    return VT_mutated

In [102]:
VT

[1, 2, 3, 4, 5, 6, 7, 8]

In [103]:
VT2 = mutacao(VT)
VT, VT2, VT != VT2

([1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8], False)

### Crossover

In [104]:
def crossover(Parent1, Parent2):

    N = len(Parent1)

    # ponto de corte
    c = np.random.randint(1, N-1)

    # crossover no ponto de corte
    # gerando dois filhos
    child1 = list(Parent1[:c]) + list(Parent2[c:])
    child2 = list(Parent2[:c]) + list(Parent1[c:])

    return child1, child2

In [105]:
VT1 = [1,1,1,1,1,1,1,1]
VT2 = [2,2,2,2,2,2,2,2]

In [106]:
crossover(VT1,VT2)

([1, 2, 2, 2, 2, 2, 2, 2], [2, 1, 1, 1, 1, 1, 1, 1])

### Seleciona pais

In [107]:
# Selecao por torneio
def selecao(Populacao):
    Candidato1 = random.choice(Populacao)
    Candidato2 = random.choice(Populacao)

    a1 = conta_ataques(Candidato1)
    a2 = conta_ataques(Candidato2)
    #print(a1,a2)

    # eleito o candidato com menor custo
    eleito = Candidato1 if a1<=a2 else Candidato2

    return eleito


In [108]:
selecao([VT1,VT2])

[1, 1, 1, 1, 1, 1, 1, 1]

### Gera Indivíduo

In [109]:
def gera_individuo(n_cols):
    # individuo é um Vetor (N) em que cada posicação
    # representa uma coluna indicando as respectivas
    # linhas ocupadas pelas rainhas em um tabuleiro (NxN).

    # VT = [low, high) x n_cols

    VT = np.random.randint(low=1, high=n_cols+1, size=n_cols)
    return VT

In [110]:
N=8
gera_individuo(N)

array([3, 1, 5, 7, 4, 8, 6, 2])

### Gera População

In [111]:
def gera_populacao_inicial(N, tam_pop):
    # N:       tamanho do tabuleiro (NxN)
    # tam_pop: tamanho da população
    populacao = []
    for _ in range(tam_pop):
        individuo = gera_individuo(N)

        populacao.append(individuo)

    return populacao

In [112]:
N = 8
tam_pop = 10
gera_populacao_inicial(N, tam_pop)

[array([5, 4, 3, 7, 5, 6, 3, 6]),
 array([3, 5, 4, 7, 8, 4, 3, 6]),
 array([6, 4, 6, 1, 1, 1, 5, 3]),
 array([1, 4, 8, 4, 7, 5, 2, 5]),
 array([8, 6, 7, 1, 5, 3, 3, 3]),
 array([6, 2, 3, 5, 3, 5, 5, 1]),
 array([2, 1, 1, 8, 7, 2, 6, 6]),
 array([2, 2, 3, 6, 6, 4, 2, 4]),
 array([8, 5, 8, 3, 6, 4, 8, 6]),
 array([6, 2, 7, 7, 7, 6, 2, 7])]

## Algoritmo Genético - Implementação

In [113]:
# 1) Randomly initialize populations p
# 2) Compute fitness of population
# 3) Until convergence repeat:
#       a) Select parents from population
#       b) Crossover and generate new population
#       c) Perform mutation on new population
# 4) Calculate fitness for new population

In [121]:
def algoritmo_genetico(N, tam_pop, num_geracoes, taxa_mutacao, n_exemp):
    """
    Executa o algoritmo genético para o problema das N rainhas.

    Parâmetros:
    N: número de rainhas e tamanho do tabuleiro (NxN).
    tam_pop: tamanho da população.
    num_geracoes: número máximo de gerações por exemplo.
    taxa_mutacao: probabilidade de mutação.
    n_exemp: número de exemplos a serem gerados.

    Retorna:
    percentual de soluções encontradas.
    custo médio das gerações.
    """
    solucoes_encontradas = 0
    geracoes_necessarias = []

    # Geração dos exemplos para teste
    for i in range(n_exemp):
        # Geração da população inicial
        Populacao = gera_populacao_inicial(N, tam_pop)
        # Cálculo do custo inicial de cada indivíduo
        TuplasCustos = gera_tuplas_custos(Populacao)
        # Ordenação da população pelo custo (fitness)
        Populacao = [t[1] for t in sorted(TuplasCustos, key=lambda x: x[0])]

        for geracao in range(num_geracoes):
            nova_populacao = []
            # Garante a geração de uma população completa
            while len(nova_populacao) < tam_pop:
                # Seleção por torneio dos pais
                pai1 = selecao(Populacao)
                pai2 = selecao(Populacao)

                # Crossover dos pais para gerar filhos
                filho1, filho2 = crossover(pai1, pai2)

                # Mutação dos filhos
                filho1 = mutacao(filho1, taxa_mutacao)
                filho2 = mutacao(filho2, taxa_mutacao)

                # Adiciona os filhos à nova população
                nova_populacao.extend([filho1, filho2])

            # Avaliação da nova população (computar fitness)
            TuplasCustos = gera_tuplas_custos(nova_populacao)
            nova_populacao = [t[1] for t in sorted(TuplasCustos, key=lambda x: x[0])]
            melhor_fitness_atual = TuplasCustos[0][0]

            # Verificação de solução ótima
            if melhor_fitness_atual == 0:
                solucoes_encontradas += 1
                geracoes_necessarias.append(geracao + 1)
                break
            Populacao = nova_populacao

        # Registro do número de gerações necessárias se nenhuma solução foi encontrada
        if melhor_fitness_atual > 0:
            geracoes_necessarias.append(num_geracoes)

    # Cálculo do percentual de soluções encontradas e custo médio das gerações
    percentual_resolvidos = (solucoes_encontradas / float(n_exemp)) * 100
    custo_medio = sum(geracoes_necessarias) / len(geracoes_necessarias)
    return percentual_resolvidos, custo_medio


In [119]:
# Configurações do algoritmo
N = 8  # tamanho do tabuleiro 8 x 8
tam_pop = 16  # tamanho da população
num_geracoes = 1000  # número máximo de gerações
taxa_mutacao = 0.1  # taxa de mutação
n_exemplos = 100

percentual_resolvidos, custo_medio = algoritmo_genetico(N, tam_pop, num_geracoes, taxa_mutacao, n_exemplos)
print(f"Percentual de problemas resolvidos: {percentual_resolvidos}%")
print(f"Custo médio da busca (em gerações): {custo_medio}")

Percentual de problemas resolvidos: 40.0%
Custo médio da busca (em gerações): 729.77
